version: "3"

services:
  coordinator:
    build:
      context: .
      dockerfile: ./coordinator/Dockerfile
    ports:
      - "1234:1234"
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: postgresql://postgres:password@postgres:5432/zkopru
      POSTGRES_PASSWORD: password
    volumes:
      - type: bind
        source: ./data
        target: /zkopru/data
      - type: bind
        source: ./coordinator.kovan.json
        target: /coordinator.kovan.json
      - type: bind
        source: ./wallet.kovan.json
        target: /wallet.kovan.json
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zkopru
